[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hta-analytics"
version = "0.2.0"
authors = [
    { name="Jiri MILLEK", email="jiri.millek@fbmi.cvut.cz" }
]
description = "A comprehensive module for Health Technology Assessment (HTA).
Provides load data from "CSV/XLSX" or synthetic data generation,
variant multi-criteria decision analysis (MCDA) by methods: TOPSIS, SAW and VIKOR,
with variant normalization techniques (Min-Max, Weitendorf),
and robust weight sensitivity assessment using interval bisection algorithms."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pandas>=2.0.0",
    "numpy>=1.20.0",
    "matplotlib>=3.5.0",
    "scipy>=1.7.0"
]
